version: '3'

services:
  database:
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=grk_dev
      - PGDATA=/var/lib/postgresql/data/pgdata

  backend:
    build: .
    volumes:
      - ./:/usr/src/app
    command: rails server -b 0.0.0.0 
    environment:
      - REDIS_URL=redis://redis
      - DATABASE_HOST=database
    ports:
      - 3000:3000

  redis:
    image: redis
    ports:
      - 6380:6379
